### ISSUE TITLE
Support corev1.ConditionStatus

### ISSUE THREAD

**Issue by Avni-Sharma** [kubepreset/kubepreset#8] opened 2021-03-06 18:43 UTC
As mentioned in https://github.com/k8s-service-bindings/spec/blob/2bce14682a4155390623f2c54f687449d412c256/internal/service.binding/v1alpha2/service_binding.go#L110

update the condition attributes in the implementation

**Comment by baijum** [comment] 2021-06-12 08:15
Duplicate of #3

**Closed by baijum** 2021-06-12 08:15 UTC
Labels: help wanted, keep-open
